# Generated by Django 5.2.9 on 2025-12-09 23:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Lamborghini', 'Lamborghini'), ('Tesla', 'Tesla'), ('Bugatti', 'Bugatti')], max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('modelo', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('ano', models.IntegerField()),
                ('alugado', models.BooleanField(default=False)),
                ('placa', models.CharField(help_text='A placa deve ter exatamente 7 caracteres.', max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('200.00'))])),
                ('seguro', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('50.00'))])),
                ('ultima_revisao', models.DateField()),
                ('ipva', models.BooleanField(default=True, verbose_name='IPVA Pago')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
    ]
