# Generated by Django 5.2.8 on 2025-12-13 00:58

import carros.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='alugado',
            field=models.BooleanField(default=False, help_text='Marque só se o carro estiver alugado', verbose_name='Carro está alugado?'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(help_text='Insira o ano do carro', validators=[carros.validators.validar_ano_carro], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='ipva',
            field=models.BooleanField(default=True, help_text='Mantenha marcado se estiver em dia', verbose_name='O IPVA esta pago?'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(choices=[('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Lamborghini', 'Lamborghini'), ('Tesla', 'Tesla'), ('Bugatti', 'Bugatti')], help_text='Selecione a marca do carro', max_length=20, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(help_text='Insira o modelo do carro', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(help_text='Insira a placa do carro (com 7 caracteres e sem traços)', max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='seguro',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Campo automático: 5% do valor da diária (mínimo R$ 50,00)', max_digits=10, verbose_name='Valor do Seguro (R$)'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='ultima_revisao',
            field=models.DateField(help_text='Insira a data em que foi feita a última vistoria', validators=[carros.validators.validar_data_revisao], verbose_name='Data da ultima revisão'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, help_text='Insira o valor cobrado por dia de aluguel', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('50.00'))], verbose_name='Valor da diaria (R$)'),
        ),
    ]
