from .person import *
from .passport import *
from .reporter import *
from .article import *
from .magazine import *
from .paper import *
from .exemplo import *
from .outro import *
from .teste import *
from .publication import *