# Generated by Django 5.2.9 on 2025-12-14 19:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import gerencia_eventos.validators.validacoes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='deve ter exatamente 3 caracteres.', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Código do assento')),
                ('bloco', models.IntegerField(help_text='Número do bloco onde o assento está localizado.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Bloco')),
                ('setor', models.CharField(choices=[('Arquibancada', 'Arquibancada'), ('Cadeira', 'Cadeira'), ('Camarote', 'Camarote'), ('Pista', 'Pista')], help_text='Área do estádio/local.', max_length=20, verbose_name='Setor')),
                ('disponivel', models.BooleanField(default=False, help_text='Se desmarcado  indica que o assento está ocupado', verbose_name='Está disponível?')),
                ('preco', models.FloatField(help_text='Valor base do assento em reais (R$).', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço do assento')),
                ('acessibilidade', models.BooleanField(default=False, help_text='Marque se o assento é reservado para PCD', verbose_name='Possui acessibilidade?')),
                ('ultima_manutencao', models.DateField(blank=True, help_text='Data da última vistoria técnica (opcional)', null=True, verbose_name='Última Manutenção')),
            ],
            options={
                'verbose_name': 'Assento',
                'verbose_name_plural': 'Assentos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='O nome deve ter no mínimo 5 caracteres.', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome do Evento')),
                ('descricao', models.CharField(blank=True, help_text='Coloque aqui um resumo sobre o evento (opcional).', max_length=1000, null=True, verbose_name='Descrição')),
                ('data', models.DateField(default=django.utils.timezone.now, help_text='Data em que o evento ocorrera', verbose_name='Data do Evento')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Horário de inicio do evento.', verbose_name='Horário')),
                ('tipo_evento', models.CharField(choices=[('Jogo', 'Jogo'), ('Show de Música', 'Show de Música'), ('Outros', 'Outros')], help_text='Selecione a categoria do evento.', max_length=20, verbose_name='Tipo de evento')),
                ('capacidade', models.IntegerField(help_text='Quantidade total de pessoas permitidas no evento (entre 10 e 60.000).', validators=[gerencia_eventos.validators.validacoes.validar_capacidade_evento], verbose_name='Capacidade Máxima')),
                ('cobertura_campo', models.BooleanField(default=False, help_text='Marque se o local possui cobertura contra chuva.', verbose_name='Cobertura de Campo?')),
                ('organizador', models.CharField(help_text='Nome da empresa ou pessoa responsável pelo evento.', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Organizador')),
                ('ingressos_disponiveis', models.IntegerField(editable=False, help_text='Este campo é calculado automaticamente pelo sistema.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingressos Disponíveis')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo (mínimo 10 caracteres)', max_length=150, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome do Titular')),
                ('email', models.EmailField(help_text='Endereço para envio do comprovante.', max_length=254, verbose_name='E-mail')),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Compra')),
                ('preco', models.FloatField(help_text='Preço final pago pelo cliente', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Pago')),
                ('tipo_ingresso', models.CharField(choices=[('Inteira', 'Inteira'), ('Meia Entrada', 'Meia Entrada'), ('Vip', 'Vip')], help_text='Inteira, Meia ou VIP.', max_length=20, verbose_name='Tipo de Ingresso')),
                ('pagamento', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], help_text='Método utilizado para quitar o ingresso.', max_length=20, verbose_name='Forma de Pagamento')),
                ('checkin', models.BooleanField(default=False, help_text='marque apenas se o pagamento foi confirmado e o cliente entrou', verbose_name='Check-in Realizado')),
                ('acesso', models.DateTimeField(blank=True, help_text='Momento exato da entrada (catraca).', null=True, verbose_name='Data/Hora do Acesso')),
                ('assento', models.OneToOneField(blank=True, help_text='Deixe em branco para ingressos de Pista(opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerencia_eventos.assento', verbose_name='Assento Marcado')),
                ('evento', models.ForeignKey(help_text='Selecione o evento para este ingresso', on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='gerencia_eventos.evento')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
            },
        ),
    ]
