# Generated by Django 5.0 on 2025-12-15 14:27

import aula.validators.cod
import aula.validators.funcoes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Magazine', max_length=100, verbose_name='Magazine Name')),
                ('edition', models.IntegerField(help_text='The edition of the Magazine', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Insira o título da reportagem', max_length=100, verbose_name='Title')),
                ('pub_date', models.DateField(verbose_name='Published in')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the person', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('birthdate', models.DateField(help_text='Insert your birthdate', verbose_name='Birthdate')),
                ('cpf', models.CharField(help_text='Insert your CPF Number without dots', max_length=11, validators=[django.core.validators.MinLengthValidator(11), aula.validators.funcoes.validate_cpf])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reporter Name', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Reporter')),
                ('cpf', models.CharField(help_text='Insert your CPF Number without dots', max_length=11, validators=[django.core.validators.MinLengthValidator(11), aula.validators.funcoes.validate_cpf])),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Passport', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Passport Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
                ('owner', models.OneToOneField(help_text='Owner', on_delete=django.db.models.deletion.CASCADE, to='aula.person', verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obs', models.TextField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.person')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.magazine')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, through='aula.Publication', to='aula.magazine'),
        ),
        migrations.AddField(
            model_name='paper',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.reporter'),
        ),
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(blank=True, help_text='Digite o cod\\ para o exemplo (opcional)', max_length=10, validators=[django.core.validators.MinLengthValidator(10), aula.validators.cod.CodValidator('4444444444'), aula.validators.funcoes.validate_par])),
                ('nome', models.CharField(help_text='Digite o nome para o exemplo (opcional)', max_length=15, validators=[django.core.validators.MinLengthValidator(3)])),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.paper')),
                ('people', models.ManyToManyField(blank=True, null=True, related_name='people', to='aula.person')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula.person')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula.reporter')),
            ],
            options={
                'permissions': [('generate_code_exemplo', 'can generate new codes')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Insira o título da reportagem', max_length=100, verbose_name='Title')),
                ('pub_date', models.DateField(verbose_name='Published in')),
                ('magazines', models.ManyToManyField(to='aula.magazine')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(max_length=255, verbose_name='Teste')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.paper')),
                ('revistas', models.ManyToManyField(to='aula.magazine')),
            ],
            options={
                'verbose_name': 'Teste',
            },
        ),
    ]
