# Generated by Django 6.0 on 2026-01-04 22:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_id', models.CharField(help_text='Formato desejado: UC1000000214', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='ID do Canal')),
                ('canal_nome', models.CharField(help_text='Nome', max_length=100, verbose_name='Nome do Canal')),
                ('canal_inscritos', models.PositiveIntegerField(default=0, help_text='Canal Inscritos', verbose_name='Quantidade de inscritos no canal')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(help_text='Formato desejado: PL100000158', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='ID da Playlist')),
                ('nome', models.CharField(help_text='Insira o nome da Playlist', max_length=255, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome da Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='ID do Vídeo', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Exemplo: GboIRoL3u6a')),
                ('url', models.URLField(help_text='Link do video', unique=True, verbose_name='URL')),
                ('titulo', models.CharField(help_text='Titulo', max_length=100, verbose_name='Titulo')),
                ('likes', models.PositiveIntegerField(default=0, help_text='Quantidade de likes', verbose_name='Likes')),
                ('dislikes', models.PositiveIntegerField(default=0, help_text='Quantidade de dislikes', verbose_name='Dislikes')),
                ('salvos', models.PositiveIntegerField(default=0, help_text='Quantidade de salvos', verbose_name='Salvos')),
                ('downloads', models.PositiveIntegerField(default=0, help_text='Quantidade de downloads', verbose_name='Downloads')),
                ('duracao', models.TimeField(help_text='Duração do vídeo', verbose_name='Durção')),
                ('comentarios', models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de comentários do vídeo', null=True, verbose_name='Comentários')),
                ('qualidade_px', models.PositiveIntegerField(default=0, help_text='Resolução do vídeo', validators=[django.core.validators.MinValueValidator(144)], verbose_name='Resolução')),
                ('palavras_chave', models.JSONField(default=list, help_text='Palavras Chave', verbose_name='Palavras Chave separadas por ;')),
                ('descricao', models.TextField(help_text='Descrição', max_length=5000, verbose_name='Descrição')),
                ('data_postagem', models.DateField(help_text='Data da Postagem', verbose_name='Data da Postagem')),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('NAO_LISTADO', 'Não Listado')], help_text='Visibilidade', max_length=100, verbose_name='Visibilidade')),
                ('idioma', models.CharField(blank=True, help_text='Idioma', max_length=5, null=True, verbose_name='Formato desejado: pt-BR ou pt')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_youtube.canal')),
                ('categorias', models.ManyToManyField(to='app_youtube.categoria', verbose_name='Categorias')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_youtube.playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
