# Generated by Django 6.0 on 2026-01-04 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição', max_length=5000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='video',
            name='qualidade_px',
            field=models.PositiveIntegerField(default=144, help_text='Resolução do vídeo', validators=[django.core.validators.MinValueValidator(144)], verbose_name='Resolução'),
        ),
    ]
